"""empty message

Revision ID: 6631788358a8
Revises: 951739cf8e4b
Create Date: 2022-12-20 16:18:05.543856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6631788358a8'
down_revision = '951739cf8e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
