"""empty message

Revision ID: 951739cf8e4b
Revises: 061d0b885c86
Create Date: 2022-12-20 16:17:16.181184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951739cf8e4b'
down_revision = '061d0b885c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
